#YAML-based pipelines are included as alternative and reference implementations to support PR-level validation, CI/CD portability, GitOps workflows, and potential migration to other CI platforms.

stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: myrepo/backend
  HELM_CHART: helm/backend

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest
  only:
    - develop
    - release/*
    - main

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
  only:
    - develop
    - release/*
    - main

deploy_dev:
  stage: deploy
  script:
    - helm upgrade --install backend $HELM_CHART \
      -f helm/values-global.yaml \
      -f helm/backend/values-dev.yaml \
      --set image.tag=$CI_COMMIT_SHA \
      -n app-dev
  only:
    - develop

deploy_qat:
  stage: deploy
  script:
    - helm upgrade --install backend $HELM_CHART \
      -f helm/values-global.yaml \
      -f helm/backend/values-qat.yaml \
      --set image.tag=$CI_COMMIT_SHA \
      -n app-qat
  only:
    - release/*
